#!/usr/bin/env bash

exec 100> /tmp/gsde-display-$GS_DESKTOP_ID.lock
flock -n 100 || exit 1

/usr/local/bin/nxnotify show-panel --title "Display Brightness" --info "decrease..." --hide-panel 1
/Library/bin/nxdisplay --decrease
