#!/usr/bin/env bash
GSDESKTOP_BINDIR="/usr/local/bin"
WMAKER_BINDIR="/opt/WindowMaker/bin"

# initate logout
${GSDESKTOP_BINDIR}/nxworkspace --logout
sleep 0.5

# we should be logging out now
${GSDESKTOP_BINDIR}/nxworkspace --ping && exit

function status {
  echo "$1"
   ${WMAKER_BINDIR}/wmshowstatus "$1" "darkgray"
}

function logout_process {
  status "logging out"
  ${GSDESKTOP_BINDIR}/nxworkspace --hide
  C=10
  while [ "$C" -ne 0 ];do
    ${GSDESKTOP_BINDIR}/nxworkspace --ping 
    RV=$?
    if [ "$RV" -eq 1 ];then 
      break
    fi

    # still in logging out
    C=$((C - 1))

    status "wait for applications to terminate $C"
    sleep 1
  done

  WM_PID=`cat /tmp/$UID-wm.pid`
  sleep 0.5

  xrefresh
  if [ -n "$WM_PID" ];then
    status "terminating WM"
    kill -HUP $WM_PID
  fi
}

LOG="/tmp/$UID-logout.log"
(logout_process > $LOG) &
